volumes:
  app-vol:
networks:
  app-net:

services:
  app-node:
    depends_on:
      - postgres-app
      - nginx-app
    build: .
    ports:
      - 3000:3000
    network:
      - app-net
  nginx-app:
    image: nginx:latest
    ports:
      - 80:80
    networks:
      - app-net
  postgres-app:
    image: postgres:latest
    ports:
     - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - app-vol:/var/lib/postgresql/data
    network:
      - app-net