apiVersion: v1
kind: Service
metadata:
  name: deploy
  namespace: default
spec:
  selector:
    app: deploy
  type: ClusterIP
  ports:
  - name: deploy
    protocol: TCP
    port: 8080
    targetPort: 8080