apiVersion: apps/v1
kind: Deployment
metadata:
  name:  deploy
  namespace: default
  labels:
    app:  deploy
spec:
  selector:
    matchLabels:
      app: deploy
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  deploy
    spec:
      containers:
      - name:  deploy
        image:  jonathassousa035/trabalhofinal:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3000
          name:  deploy
      restartPolicy: Always
